# Generated by Django 5.2.17 on 2026-09-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emp_ID', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
